/**
 * Phase 1 §5.2 — Atomic Vietnamese ingredients (curated).
 *
 * Editing rules:
 *   - UUIDs are FROZEN. Never regenerate. Add new entries with new uuids.
 *   - Macro values are per 100 g (or 100 ml for liquids), per `nutrition_basis_unit`.
 *   - Every entry MUST have non-empty `source_citation` pointing into ./sources/.
 *   - For staples (whitelist in build-ingredients.ts), `category: 'staple'` is allowed
 *     even if no dish references them.
 *   - Determinism: build script sorts by id before serialising; author order here is
 *     grouped by category for human review.
 *
 * STATE: §5.2.4 — full atomic set required to back the 20 curated dishes plus the
 * 7 composite broth/sauce recipes. Macros pulled from Wikipedia VI / USDA aligned
 * Vietnamese published values; entries marked is_approximate when in doubt.
 */
import type { IngredientSeed } from '../types';

export const VI_INGREDIENTS: ReadonlyArray<IngredientSeed> = [
  // ─── Staples (AC2 whitelist) ────────────────────────────────────────────
  {
    id: '7c4e8b1a-0002-4000-8000-000000000001',
    name_vi: 'nước mắm',
    name_en: 'Vietnamese fish sauce',
    category: 'staple',
    nutrition_basis_unit: 'ml',
    nutrition_basis_quantity: 100,
    calories: 35,
    protein: 5.1,
    carbs: 3.6,
    fat: 0,
    fiber: 0,
    density_g_per_ml: 1.2,
    default_unit_id: 'tbsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#nuoc-mam',
    is_approximate: true,
    notes: 'Average across 35°N grade. Refine if user feedback flags drift.',
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000002',
    name_vi: 'muối',
    name_en: 'Salt',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'tsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#muoi',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000003',
    name_vi: 'đường',
    name_en: 'Sugar (white, granulated)',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 387,
    protein: 0,
    carbs: 100,
    fat: 0,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'tsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#duong',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000004',
    name_vi: 'dầu ăn',
    name_en: 'Cooking oil (vegetable)',
    category: 'staple',
    nutrition_basis_unit: 'ml',
    nutrition_basis_quantity: 100,
    calories: 824,
    protein: 0,
    carbs: 0,
    fat: 91.5,
    fiber: 0,
    density_g_per_ml: 0.92,
    default_unit_id: 'tbsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#dau-an',
    is_approximate: true,
    notes: 'Generic blended vegetable oil; refine per cuisine if relevant.',
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000005',
    name_vi: 'hành tím',
    name_en: 'Shallot',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 72,
    protein: 2.5,
    carbs: 16.8,
    fat: 0.1,
    fiber: 3.2,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#hanh-tim',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000006',
    name_vi: 'hành lá',
    name_en: 'Scallion (green onion)',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 32,
    protein: 1.8,
    carbs: 7.3,
    fat: 0.2,
    fiber: 2.6,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#hanh-la',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000007',
    name_vi: 'tỏi',
    name_en: 'Garlic',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 149,
    protein: 6.4,
    carbs: 33.1,
    fat: 0.5,
    fiber: 2.1,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#toi',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000008',
    name_vi: 'gừng',
    name_en: 'Ginger root',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 80,
    protein: 1.8,
    carbs: 17.8,
    fat: 0.7,
    fiber: 2.0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#gung',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000009',
    name_vi: 'sả',
    name_en: 'Lemongrass',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 99,
    protein: 1.8,
    carbs: 25.3,
    fat: 0.5,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#sa',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000000a',
    name_vi: 'ớt',
    name_en: 'Chili pepper, fresh',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 40,
    protein: 1.9,
    carbs: 8.8,
    fat: 0.4,
    fiber: 1.5,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#ot',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000000b',
    name_vi: 'tiêu',
    name_en: 'Black pepper, ground',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 251,
    protein: 10.4,
    carbs: 64.0,
    fat: 3.3,
    fiber: 25.3,
    density_g_per_ml: null,
    default_unit_id: 'tsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#tieu',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000000c',
    name_vi: 'bột ngọt',
    name_en: 'MSG (monosodium glutamate)',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 0,
    protein: 12.3,
    carbs: 0,
    fat: 0,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'tsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#bot-ngot',
    is_approximate: true,
    notes: 'Conventional reporting: ~0 kcal usable energy though mass-N is present.',
  },

  // ─── Common atomics (proteins, carbs) used by §5.2.3+ composites/dishes ───
  {
    id: '7c4e8b1a-0002-4000-8000-000000000101',
    name_vi: 'ức gà',
    name_en: 'Chicken breast, raw',
    category: 'meat',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#uc-ga',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000102',
    name_vi: 'bánh phở tươi',
    name_en: 'Fresh rice noodles for phở',
    category: 'grain',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 109,
    protein: 1.8,
    carbs: 25.0,
    fat: 0.2,
    fiber: 0.4,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#banh-pho',
    is_approximate: true,
  },

  // ─── §5.2.4 atomics: proteins ────────────────────────────────────────────
  {
    id: '7c4e8b1a-0002-4000-8000-000000000103',
    name_vi: 'thịt bò nạc',
    name_en: 'Lean beef, raw',
    category: 'meat',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#thit-bo-nac',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000104',
    name_vi: 'thịt heo nạc vai',
    name_en: 'Pork shoulder, lean, raw',
    category: 'meat',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 242,
    protein: 27,
    carbs: 0,
    fat: 14,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#thit-heo-nac-vai',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000105',
    name_vi: 'sườn heo',
    name_en: 'Pork ribs, raw',
    category: 'meat',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 277,
    protein: 18.6,
    carbs: 0,
    fat: 22,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#suon-heo',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000106',
    name_vi: 'tôm sú',
    name_en: 'Tiger prawn, raw',
    category: 'seafood',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#tom-su',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000107',
    name_vi: 'mực ống',
    name_en: 'Squid, raw',
    category: 'seafood',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 92,
    protein: 15.6,
    carbs: 3.1,
    fat: 1.4,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#muc-ong',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000108',
    name_vi: 'cá lóc',
    name_en: 'Snakehead fish, raw',
    category: 'seafood',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 98,
    protein: 18.2,
    carbs: 0,
    fat: 2.5,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#ca-loc',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000109',
    name_vi: 'cá basa',
    name_en: 'Basa fish, raw',
    category: 'seafood',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 124,
    protein: 18,
    carbs: 0,
    fat: 5.6,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#ca-basa',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000010a',
    name_vi: 'trứng gà',
    name_en: 'Chicken egg, whole',
    category: 'egg',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#trung-ga',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000010b',
    name_vi: 'chả lụa',
    name_en: 'Vietnamese pork roll',
    category: 'meat',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 200,
    protein: 19,
    carbs: 2,
    fat: 12,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#cha-lua',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000010c',
    name_vi: 'cua đồng',
    name_en: 'Field crab paste',
    category: 'seafood',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 87,
    protein: 12.3,
    carbs: 2.0,
    fat: 3.3,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#cua-dong',
    is_approximate: true,
  },

  // ─── §5.2.4 atomics: grains / carbs ──────────────────────────────────────
  {
    id: '7c4e8b1a-0002-4000-8000-00000000010d',
    name_vi: 'cơm trắng',
    name_en: 'Cooked white rice',
    category: 'grain',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#com-trang',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000010e',
    name_vi: 'bún tươi',
    name_en: 'Fresh rice vermicelli',
    category: 'grain',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 110,
    protein: 1.7,
    carbs: 25,
    fat: 0.2,
    fiber: 0.4,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#bun-tuoi',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000010f',
    name_vi: 'mì trứng tươi',
    name_en: 'Fresh egg noodles',
    category: 'grain',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 138,
    protein: 5,
    carbs: 27,
    fat: 0.9,
    fiber: 1.2,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#mi-trung-tuoi',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000110',
    name_vi: 'mì Quảng',
    name_en: 'Mì Quảng noodles, fresh',
    category: 'grain',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 109,
    protein: 1.8,
    carbs: 25,
    fat: 0.2,
    fiber: 0.4,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#mi-quang',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000111',
    name_vi: 'bánh mì',
    name_en: 'Vietnamese baguette',
    category: 'grain',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 265,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    fiber: 2.7,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#banh-mi',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000112',
    name_vi: 'xôi',
    name_en: 'Cooked sticky rice',
    category: 'grain',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 169,
    protein: 3.5,
    carbs: 36.5,
    fat: 0.3,
    fiber: 0.5,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#xoi',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000113',
    name_vi: 'bánh tráng',
    name_en: 'Rice paper',
    category: 'grain',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 333,
    protein: 0.5,
    carbs: 81,
    fat: 0.3,
    fiber: 1.4,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#banh-trang',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000114',
    name_vi: 'bột gạo',
    name_en: 'Rice flour',
    category: 'grain',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 366,
    protein: 6,
    carbs: 80,
    fat: 1.4,
    fiber: 2.4,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#bot-gao',
    is_approximate: true,
  },

  // ─── §5.2.4 atomics: vegetables / fruits / misc ──────────────────────────
  {
    id: '7c4e8b1a-0002-4000-8000-000000000115',
    name_vi: 'cà chua',
    name_en: 'Tomato, raw',
    category: 'vegetable',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#ca-chua',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000116',
    name_vi: 'dưa chua',
    name_en: 'Pickled mustard greens',
    category: 'vegetable',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 19,
    protein: 1.2,
    carbs: 3.5,
    fat: 0.2,
    fiber: 2.0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#dua-chua',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000117',
    name_vi: 'rau sống',
    name_en: 'Mixed fresh herbs',
    category: 'vegetable',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 28,
    protein: 2.5,
    carbs: 5,
    fat: 0.4,
    fiber: 2.5,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#rau-song',
    is_approximate: true,
    notes: 'Average across lettuce/perilla/mint/coriander mixed plate.',
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000118',
    name_vi: 'nấm rơm',
    name_en: 'Straw mushroom',
    category: 'vegetable',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 28,
    protein: 3.8,
    carbs: 4.6,
    fat: 0.5,
    fiber: 2.6,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#nam-rom',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000119',
    name_vi: 'dứa',
    name_en: 'Pineapple, raw',
    category: 'fruit',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 50,
    protein: 0.5,
    carbs: 13,
    fat: 0.1,
    fiber: 1.4,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#dua',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000011a',
    name_vi: 'giá đỗ',
    name_en: 'Mung bean sprouts',
    category: 'vegetable',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 30,
    protein: 3,
    carbs: 5.9,
    fat: 0.2,
    fiber: 1.8,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#gia-do',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000011b',
    name_vi: 'me chua',
    name_en: 'Tamarind paste',
    category: 'condiment',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 239,
    protein: 2.8,
    carbs: 62.5,
    fat: 0.6,
    fiber: 5.1,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#me-chua',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000011c',
    name_vi: 'đậu phụ',
    name_en: 'Tofu, firm',
    category: 'vegetable',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    fiber: 0.3,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#dau-phu',
    is_approximate: false,
  },
];
