/**
 * Phase 1 §5.2 — Atomic Vietnamese ingredients (curated).
 *
 * Editing rules:
 *   - UUIDs are FROZEN. Never regenerate. Add new entries with new uuids.
 *   - Macro values are per 100 g (or 100 ml for liquids), per `nutrition_basis_unit`.
 *   - Every entry MUST have non-empty `source_citation` pointing into ./sources/.
 *   - For staples (whitelist in build-ingredients.ts), `category: 'staple'` is allowed
 *     even if no dish references them.
 *   - Determinism: build script sorts by id before serialising; author order here is
 *     grouped by category for human review.
 *
 * STATE: §5.2.2 — full Vietnamese kitchen staple set + a few atomics needed to
 * wire composites/dishes. Additional atomics are appended in §5.2.3 / §5.2.4 as
 * composite/dish authoring lands.
 */
import type { IngredientSeed } from '../types';

export const VI_INGREDIENTS: ReadonlyArray<IngredientSeed> = [
  // ─── Staples (AC2 whitelist) ────────────────────────────────────────────
  {
    id: '7c4e8b1a-0002-4000-8000-000000000001',
    name_vi: 'nước mắm',
    name_en: 'Vietnamese fish sauce',
    category: 'staple',
    nutrition_basis_unit: 'ml',
    nutrition_basis_quantity: 100,
    calories: 35,
    protein: 5.1,
    carbs: 3.6,
    fat: 0,
    fiber: 0,
    density_g_per_ml: 1.2,
    default_unit_id: 'tbsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#nuoc-mam',
    is_approximate: true,
    notes: 'Average across 35°N grade. Refine if user feedback flags drift.',
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000002',
    name_vi: 'muối',
    name_en: 'Salt',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'tsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#muoi',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000003',
    name_vi: 'đường',
    name_en: 'Sugar (white, granulated)',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 387,
    protein: 0,
    carbs: 100,
    fat: 0,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'tsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#duong',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000004',
    name_vi: 'dầu ăn',
    name_en: 'Cooking oil (vegetable)',
    category: 'staple',
    nutrition_basis_unit: 'ml',
    nutrition_basis_quantity: 100,
    calories: 824,
    protein: 0,
    carbs: 0,
    fat: 91.5,
    fiber: 0,
    density_g_per_ml: 0.92,
    default_unit_id: 'tbsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#dau-an',
    is_approximate: true,
    notes: 'Generic blended vegetable oil; refine per cuisine if relevant.',
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000005',
    name_vi: 'hành tím',
    name_en: 'Shallot',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 72,
    protein: 2.5,
    carbs: 16.8,
    fat: 0.1,
    fiber: 3.2,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#hanh-tim',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000006',
    name_vi: 'hành lá',
    name_en: 'Scallion (green onion)',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 32,
    protein: 1.8,
    carbs: 7.3,
    fat: 0.2,
    fiber: 2.6,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#hanh-la',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000007',
    name_vi: 'tỏi',
    name_en: 'Garlic',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 149,
    protein: 6.4,
    carbs: 33.1,
    fat: 0.5,
    fiber: 2.1,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#toi',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000008',
    name_vi: 'gừng',
    name_en: 'Ginger root',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 80,
    protein: 1.8,
    carbs: 17.8,
    fat: 0.7,
    fiber: 2.0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#gung',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000009',
    name_vi: 'sả',
    name_en: 'Lemongrass',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 99,
    protein: 1.8,
    carbs: 25.3,
    fat: 0.5,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#sa',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000000a',
    name_vi: 'ớt',
    name_en: 'Chili pepper, fresh',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 40,
    protein: 1.9,
    carbs: 8.8,
    fat: 0.4,
    fiber: 1.5,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#ot',
    is_approximate: true,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000000b',
    name_vi: 'tiêu',
    name_en: 'Black pepper, ground',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 251,
    protein: 10.4,
    carbs: 64.0,
    fat: 3.3,
    fiber: 25.3,
    density_g_per_ml: null,
    default_unit_id: 'tsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#tieu',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-00000000000c',
    name_vi: 'bột ngọt',
    name_en: 'MSG (monosodium glutamate)',
    category: 'staple',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 0,
    protein: 12.3,
    carbs: 0,
    fat: 0,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'tsp',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#bot-ngot',
    is_approximate: true,
    notes: 'Conventional reporting: ~0 kcal usable energy though mass-N is present.',
  },

  // ─── Common atomics (proteins, carbs) used by §5.2.3+ composites/dishes ───
  {
    id: '7c4e8b1a-0002-4000-8000-000000000101',
    name_vi: 'ức gà',
    name_en: 'Chicken breast, raw',
    category: 'meat',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#uc-ga',
    is_approximate: false,
  },
  {
    id: '7c4e8b1a-0002-4000-8000-000000000102',
    name_vi: 'bánh phở tươi',
    name_en: 'Fresh rice noodles for phở',
    category: 'grain',
    nutrition_basis_unit: 'g',
    nutrition_basis_quantity: 100,
    calories: 109,
    protein: 1.8,
    carbs: 25.0,
    fat: 0.2,
    fiber: 0.4,
    density_g_per_ml: null,
    default_unit_id: 'g',
    source: 'wikipedia-vi',
    source_citation: 'sources/wikipedia-vi.md#banh-pho',
    is_approximate: true,
  },
];
