/**
 * NetworkStore — wraps `@capacitor/network` with an Angular Signal so that
 * UI can reactively show/hide AI features when the device is offline.
 *
 * Source-of-truth: `docs/5-development/phase-1.5b-ai-foundation.md` §3.6.
 *
 * Usage:
 *   const net = inject(NetworkStore);
 *   net.start();                       // call once at app startup
 *   if (!net.online()) { ... }         // signal read
 *
 * Listener cleanup: `start()` returns a `PluginListenerHandle`. `stop()`
 * removes it. Test code MUST call `stop()` in `afterEach` to avoid leaks.
 *
 * Why a DI token for the plugin?
 *   The Capacitor `Network` export is a Proxy generated by `registerPlugin`,
 *   which means `spyOn(Network, 'getStatus')` and direct property assignment
 *   are both unreliable in Karma/Jasmine. We expose the plugin behind a DI
 *   token so tests can swap a plain object factory cleanly.
 */

import { Injectable, InjectionToken, inject, signal } from '@angular/core';
import { Network, type ConnectionStatus } from '@capacitor/network';
import type { PluginListenerHandle } from '@capacitor/core';

export interface NetworkPluginLike {
  getStatus(): Promise<ConnectionStatus>;
  addListener(
    event: 'networkStatusChange',
    cb: (status: ConnectionStatus) => void,
  ): Promise<PluginListenerHandle>;
}

export const NETWORK_PLUGIN = new InjectionToken<NetworkPluginLike>('NETWORK_PLUGIN', {
  providedIn: 'root',
  factory: () => ({
    getStatus: () => Network.getStatus(),
    addListener: (event, cb) => Network.addListener(event, cb),
  }),
});

@Injectable({ providedIn: 'root' })
export class NetworkStore {
  private readonly plugin = inject(NETWORK_PLUGIN);

  /** True when device has any connection (wifi/cellular/ethernet). */
  readonly online = signal(true);

  private handle: PluginListenerHandle | undefined;

  /**
   * Subscribe to Capacitor network events. Idempotent — safe to call twice.
   * Reads the initial state synchronously and seeds the signal.
   */
  async start(): Promise<void> {
    if (this.handle) return;
    try {
      const status = await this.plugin.getStatus();
      this.applyStatus(status);
      this.handle = await this.plugin.addListener('networkStatusChange', (next) =>
        this.applyStatus(next),
      );
    } catch (err) {
      // Web / non-Capacitor environments may throw — assume online.
      console.warn('[NetworkStore] start failed, defaulting online:', err);
      this.online.set(true);
    }
  }

  /** Tear down listener (used in tests + on app shutdown). */
  async stop(): Promise<void> {
    if (this.handle) {
      await this.handle.remove();
      this.handle = undefined;
    }
  }

  private applyStatus(status: ConnectionStatus): void {
    this.online.set(status.connected);
  }
}
